- name: Copy auth configuration file
  ansible.builtin.template:
    src: "{{ COMPONENT }}.service"
    dest: /etc/systemd/system/{{ COMPONENT }}.service

- name: Start service auth-service
  ansible.builtin.service:
    name: {{ COMPONENT }}
    daemon_reload: yes
    enabled: yes
    state: restarted
